# impeccable v4.0.4 (EricOS .agents/skills/impeccable) — command data, sourced from SKILL.md + reference/*.md
# group: (id, region label, archify node type, legend label)
GROUPS = [
 ("ctx",   "Setup",     "cloud",      "context / setup"),
 ("plan",  "Plan & build",        "messagebus", "plan / build"),
 ("diag",  "Diagnose",            "security",   "diagnose (report only)"),
 ("fix",   "Fix · choose as needed",        "backend",    "fix / refine"),
 ("style", "Style · choose as needed",               "frontend",   "style / enhance"),
 ("motion","Motion · choose as needed",        "frontend",   None),
 ("fin",   "Polish last",              "external",   "finish"),
  ("util",  "Utilities · use independently", "database", "utilities"),
]

# id, label, group, trigger (node sublabel), steps, inputs, output, requires, feeds-into, source
C = [
 ("menu","/impeccable","ctx","no arg · what next?",
  ["Read context.mjs result","NO_PRODUCT_MD → lead with init","Else read context-signals.mjs","Run detect.mjs once on scan targets (web only)","Show 2–3 picks + full menu; never auto-run"],
  "context signals, git changes, detector hits","2–3 recommended commands to type","—","init, document, critique, polish, audit, live, (any verb)","routing.md"),
 ("init","init","ctx","no PRODUCT.md yet",
  ["Load current state (update, never overwrite)","Explore repo before asking","Interview: users, purpose, constraints (≥1 round)","Write PRODUCT.md (schema 1)","Configure live mode if web + runnable","Recommend next command / resume caller"],
  "repo evidence + user answers","PRODUCT.md (+ .impeccable/live/config.json)","—","shape, craft/new work, document, live","init.md"),
 ("document","document","ctx","code, no DESIGN.md",
  ["Scan: find tokens, Tailwind, themes, components","Auto-extract colors, type, elevation, components","Stage YAML frontmatter","Ask 2 rounds of descriptive language","Write DESIGN.md (Stitch format) + sidecar","Seed mode (no code): route via init + new-work workshop"],
  "codebase tokens/components (scan) or PRODUCT.md (seed)","DESIGN.md + .impeccable/design.json","init (seed mode only)","every later command (via context.mjs)","document.md"),
 ("shape","shape","plan","plan before code",
  ["Discovery interview: purpose, people, outcome","Round 2 only for material gaps","Resolve direction via new-work (new surfaces only)","Write the smallest useful brief","Confirm, then stop — no code"],
  "user answers, PRODUCT.md","Confirmed design brief (no code)","init (if no PRODUCT.md, via new-work)","craft / new work (build)","shape.md"),
 ("craft","craft","plan","new build · redesign",
  ["Alias: runs the normal new-work flow","Decide what is already true","Ask one round","Choose invention level; concept-seed.mjs roll","Commit world + direction contract","Visualize 3 comps (if image gen)","Build → finish reviewer → documenter"],
  "PRODUCT.md, DESIGN.md, brief","Built surface + direction contract + DESIGN.md","init (PRODUCT.md)","document (documenter at finish)","craft.md → new-work.md"),
 ("critique","critique","diag","review · feedback",
  ["Resolve target + slug","A: design review sub-agent (heuristics /40)","B: detector + browser sub-agent (isolated)","Synthesize: P0–P3 issues, personas, cognitive load","Persist snapshot + trend","Ask user priority/scope","Recommend commands, end with polish"],
  "target file/URL, detect.mjs, ignore.md","Report /40 + snapshot in .impeccable/critique/","—","polish (reads snapshot), any of 19 verbs","critique.md"),
 ("audit","audit","diag","a11y · perf check",
  ["Scan 5 dimensions: a11y, perf, theming, responsive, integrity","Score each 0–4 (/20)","Integrity verdict first","Findings by P0–P3 with suggested command","Recommend commands, end with polish (no fixes)"],
  "target code (native: audit.native.md)","Health score /20 + P0–P3 action plan","—","harden, optimize, adapt, … then polish","audit.md"),
 ("harden","harden","fix","edge cases · i18n",
  ["Assess hardening needs","Text overflow & wrapping","i18n","Error handling","Edge cases + input validation","A11y + performance resilience","Verify → hand to polish"],
  "target, real-world data ranges","Resilient states (errors, overflow, i18n)","—","polish","harden.md"),
 ("clarify","clarify","fix","confusing copy",
  ["Audit the language","Set message hierarchy","Rewrite actions, forms, errors, states, help","Voice, a11y, localization","Verify → hand to polish"],
  "audience knowledge + emotional state","Clearer microcopy, labels, errors","—","polish","clarify.md"),
 ("adapt","adapt","fix","mobile · breakpoints",
  ["Assess adaptation challenge","Plan strategy (mobile/tablet/desktop/print/email)","Implement breakpoints, touch, content, nav","Verify → hand to polish"],
  "target platforms/devices (native: adapt.native.md)","Layout adapted to the new context","—","polish","adapt.md"),
 ("optimize","optimize","fix","slow · janky",
  ["Assess: find the actual bottleneck","Loading, rendering, animation, framework, network","Core Web Vitals (LCP, INP, CLS)","Measure before/after","Verify → hand to polish"],
  "target + measurements","Faster UI + before/after numbers","—","polish","optimize.md"),
 ("onboard","onboard","fix","first-run · empty",
  ["Assess onboarding needs (aha moment)","Apply principles: show, optional, time-to-value","Design onboarding / discovery / tours","Empty-state design","Verify → hand to polish"],
  "aha moment + user experience level","First-run flow and empty states","—","polish","onboard.md"),
 ("distill","distill","fix","cluttered UI",
  ["Assess current state","Plan simplification","Simplify IA, visual, layout, interaction, content, code","Verify","Document removed complexity → polish"],
  "target","Simpler UI + list of what was removed","—","polish","distill.md"),
 ("layout","layout","style","spacing · hierarchy",
  ["Pick visitor mode","Two isolated assessments (design + detector)","Set the spatial thesis","Apply inside current world","Verify → hand to polish"],
  "target, DESIGN.md","Restructured layout and rhythm","—","polish; new identity → new work","layout.md"),
 ("typeset","typeset","style","fonts · type scale",
  ["Pick visitor mode","Two isolated assessments (design + detector)","Set the type system","Apply","Verify → hand to polish"],
  "target, DESIGN.md fonts","Type roles, scale, measure fixed","—","polish; new identity → new work + DESIGN.md","typeset.md"),
 ("colorize","colorize","style","gray · dull",
  ["Pick visitor mode","Audit before choosing","Choose a color strategy","Apply at system scale","Contrast + perception check","Verify → hand to polish"],
  "existing brand colors, DESIGN.md","Color roles applied across the system","—","polish; new identity → new work","colorize.md"),
 ("bolder","bolder","style","bland · too safe",
  ["Scope is sovereign: touch only the target","Diagnose why it reads flat","Amplify what the system already owns","Skeleton test","Before-you-finish checks → polish"],
  "target section + what stays untouched","One section amplified, same brand","—","polish","bolder.md"),
 ("quieter","quieter","style","too loud · garish",
  ["Pick visitor mode","Assess current state","Plan refinement","Reduce color, weight, motion; simplify","Verify → hand to polish"],
  "target","Calmer UI, personality kept","—","polish","quieter.md"),
 ("animate","animate","motion","needs motion",
  ["Pick visitor mode","Find the motion's job","Set the motion thesis","Choose material, timing, easing","Implement to runtime + reduced motion","Verify → hand to polish"],
  "target + performance constraints","Purposeful motion implemented","—","polish","animate.md"),
 ("delight","delight","motion","wants personality",
  ["Pick visitor mode","Find the opportunity","Define one delight thesis","Build for the emotional moment (loads animate)","Protect the experience","Verify → hand to polish"],
  "brand's emotional range","One memorable moment, built","—","animate (for motion), polish","delight.md"),
 ("overdrive","overdrive","motion","wow · go all out",
  ["Propose 2–3 directions, user picks","Assess what extraordinary means here","Pick from toolkit (shaders, scroll, physics…)","Implement with progressive enhancement","Iterate in browser + verify"],
  "target + user's chosen direction","Technically ambitious implementation","—","—","overdrive.md"),
 ("polish","polish","fin","before shipping",
  ["Establish the system (DESIGN.md, tokens)","Gather evidence + latest critique snapshot","Triage functional vs cosmetic","Polish the whole path","Verify every state + clean diff"],
  "DESIGN.md, critique snapshot, quality bar","Shippable path + clean source diff","—","bolder / redesign (if concept is wrong)","polish.md"),
 ("extract","extract","ctx","drift · 3+ repeats",
  ["Discover the design system (ask if none)","Identify patterns used 3+ times","Plan extraction","Extract & enrich components/tokens","Migrate all uses","Document"],
  "codebase repeats","Shared tokens + components, migrated uses","—","— (no command link in source)","extract.md"),
 ("live","live","util","dev server running",
  ["Boot live.mjs (+ live-setup on first run)","Open the app URL","Background poll loop","On generate: load verb ref, 3 variants via HMR","Accept / discard → write source","Exit cleanup"],
  "running dev server, PRODUCT.md, DESIGN.md","Chosen variant written to source","init (configures live, optional)","— (calls 11 verb references)","live.md"),
 ("hooks","hooks","util","detector on edits",
  ["on / off / status","ignore-rule / ignore-file / ignore-value","reset","Edits .impeccable/config.json"],
  "subcommand","Hook config; detector runs after UI edits","—","—","hooks.md"),
 ("doctor","doctor","util","stale artifacts?",
  ["Run doctor.mjs --json","auto → --fix silently","mention / decide by severity","Truth drift → hand gap to init / document"],
  "PRODUCT.md, DESIGN.md, config, briefs, hook","Drift report + safe auto-fixes","—","init, document (truth drift)","doctor.md"),
 ("pin","pin / unpin","util","want a shortcut",
  ["pin.mjs pin|unpin <command>","Report result; relay stderr"],
  "command name","Standalone /<command> shortcut","—","—","SKILL.md"),
]

# Map arrows show order of use; clicked definitions retain detailed pairings.
STAGES = [
 ("ctx", "Setup", "establish context", ["init", "document", "extract", "menu"]),
 ("plan", "Plan / build", "plan, then build", ["shape", "craft"]),
 ("diag", "Diagnose", "review + report", ["critique", "audit"]),
 ("fix", "Fix", "choose as needed", ["harden", "clarify", "adapt", "optimize", "onboard", "distill"]),
 ("style", "Style", "choose as needed", ["layout", "typeset", "colorize", "bolder", "quieter"]),
 ("motion", "Motion", "choose as needed", ["animate", "delight", "overdrive"]),
 ("fin", "Polish", "always last", ["polish"]),
]
UTILITIES = ["hooks", "doctor", "pin", "live"]

# ---- v3 additions ----
# short trigger (one phrase, canvas sublabel)
TRIG = {"menu":"what next?","init":"no PRODUCT.md","document":"no DESIGN.md","shape":"plan first","craft":"build new",
"critique":"UX review","audit":"tech check","harden":"edge cases","clarify":"confusing copy","adapt":"other screens",
"optimize":"feels slow","onboard":"first run","distill":"too cluttered","layout":"spacing off","typeset":"type off",
"colorize":"too gray","bolder":"too bland","quieter":"too loud","animate":"needs motion","delight":"needs charm",
"overdrive":"wow factor","polish":"before ship","extract":"repeated UI","live":"try variants","hooks":"auto-detect",
"doctor":"stale files","pin":"shortcut"}
# plain-words definition (shown in the passport)
DEF = {
"menu":"Run /impeccable with no argument. It reads your project's state and suggests the 2–3 commands most worth running next. It never runs one for you.",
"init":"Interviews you about users, purpose and constraints, then writes PRODUCT.md. Every other command reads that file first.",
"document":"Reads your existing CSS, tokens and components and writes DESIGN.md, a visual spec that keeps later AI edits on-brand.",
"shape":"Plans a feature before any code: a short interview, then a design brief you confirm. It never writes code.",
"craft":"Builds a new surface or redesign end to end: picks a visual direction, renders comps, builds, has a fresh reviewer check it, records DESIGN.md. Deprecated name: just ask for the build.",
"critique":"A design review. Two isolated reviewers (design judgment + automated detector) score usability out of 40 and list P0–P3 issues, each with the command that fixes it.",
"audit":"A technical check of accessibility, performance, theming, responsive and implementation, scored out of 20. It reports only; it does not fix anything.",
"harden":"Makes the UI survive real data: long text, errors, empty and loading states, other languages, bad input.",
"clarify":"Rewrites labels, buttons, errors and help text so people know what happened and what to do next.",
"adapt":"Reworks the design for another screen or context (phone, tablet, print, email), not just a shrunk copy.",
"optimize":"Finds what actually makes the UI slow (loading, rendering, animation, bundle) and fixes it, with before/after numbers.",
"onboard":"Designs first-run flows and empty states that get a new user to the 'aha' moment fast.",
"distill":"Removes whatever does not earn its place: duplicate info, extra options, decorative noise.",
"layout":"Fixes structure: reading order, grouping, spacing rhythm and hierarchy, inside the current look.",
"typeset":"Fixes typography: font roles, scale, weight, line length and readability.",
"colorize":"Adds color with a purpose (hierarchy, meaning, atmosphere) to a gray or flat UI.",
"bolder":"Turns up one flat section to the confidence the rest of the page already has. Everything else stays untouched.",
"quieter":"Turns down a loud or garish design (color, weight, motion) without making it generic.",
"animate":"Adds motion that explains state and hierarchy, plus at most one authored moment. No decoration for its own sake.",
"delight":"Adds one memorable, on-brand moment of personality where the experience has earned it.",
"overdrive":"Goes technically all-out (shaders, scroll-driven effects, physics). It proposes 2–3 directions and waits for your pick first.",
"polish":"The final pass before shipping: alignment, consistency, every state, a clean diff. It reads the last critique as its to-do list.",
"extract":"Pulls UI that repeats 3+ times into shared tokens and components, then migrates every use.",
"live":"Pick an element in the running app and get 3 design variants hot-swapped in the browser. Accept one and it is written to source.",
"hooks":"Turns the automatic design detector on or off. When on, it checks every UI file edit and flags problems.",
"doctor":"Checks whether PRODUCT.md, DESIGN.md and impeccable config are stale for this version, and auto-fixes the safe parts.",
"pin":"Creates (or removes) a standalone /<command> shortcut, e.g. /polish instead of /impeccable polish.",
}
# best-practice use: what to pair it with
PAIR = {
"menu":"Start here when unsure; it points to init on a fresh project.",
"init":"Run once per project, first. Then shape or a build; document if code already exists.",
"document":"After init on existing code, or let a build write it at the finish. Re-run when the design drifts.",
"shape":"After init. Hand the confirmed brief to a build (craft).",
"craft":"init → (shape) → build. Follow with critique, then the fix commands, then polish.",
"critique":"Pair with audit to diagnose. Run the commands it suggests, then polish last; re-run to see the score move.",
"audit":"Pair with critique. Its findings go to harden, optimize, adapt…; end with polish.",
"harden":"Usually from an audit finding. Hand off to polish.",
"clarify":"Often from a critique finding. Hand off to polish.",
"adapt":"From audit's responsive findings. Hand off to polish.",
"optimize":"From audit's performance findings. Hand off to polish.",
"onboard":"Hand off to polish.",
"distill":"Often suggested by critique. Hand off to polish.",
"layout":"Pair with typeset. A new identity goes to a build instead. Then polish.",
"typeset":"Pair with layout. New fonts = new identity → build + DESIGN.md. Then polish.",
"colorize":"Opposite of quieter. A new palette identity goes to a build. Then polish.",
"bolder":"Opposite of quieter/distill. Polish suggests it when a concept is too timid. Then polish.",
"quieter":"Opposite of bolder/colorize. Hand off to polish.",
"animate":"delight uses it for motion. Hand off to polish.",
"delight":"Calls animate for motion. Hand off to polish.",
"overdrive":"Use on its own when the brief asks for wow; verify in the browser.",
"polish":"Always last, after diagnose + fixes. If the concept is wrong it suggests bolder or a redesign.",
"extract":"During setup on an existing codebase, or whenever repeated UI drifts apart. Run independently when needed.",
"live":"Needs a dev server; init sets it up. Uses the style commands' rules for its variants.",
"hooks":"Leave on while building; it catches mechanical defects as you edit.",
"doctor":"When context looks stale; it hands real gaps to init or document.",
"pin":"Pin the commands you run most (polish, critique).",
}
